env: sc2

env_args:
  continuing_episode: False
  difficulty: "7"
  game_version: null
  map_name: "3m"
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False
#  debug: True

test_greedy: True
test_nepisode: 32
test_interval: 10000.
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
run_mode: "Train"

## Start (code for test). if train: comment followings; elif test: uncomment.
#run_mode: "Test"
#batch_size_run: 1
checkpoint_path: "/home/dell/cjm/pymarl2_mask/results/models/1c3s5z_qmix_env=8_adam_td_lambda__2024-01-08_15-24-42"
##load_step: 1004113
#save_model: True
#save_replay: True
## End (code for test).
